import {
  ArrowLeft, Languages, Volume2, Video, Download,
  CheckCircle, FileText, FileDown, Printer
} from 'lucide-react';
import type { PipelineResult } from '../services/api';

interface ResultViewerProps {
  darkMode: boolean;
  result: PipelineResult;
  jobType: string;
  onBack: () => void;
}

// ── Download helpers ──────────────────────────────────────────
function downloadTxt(text: string, filename = 'translation.txt') {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function printAsPDF(originalText?: string, translatedText?: string) {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`
    <html>
      <head>
        <title>Bhasha Node – Translation</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.8; color: #111; }
          h2 { color: #4f46e5; margin-bottom: 8px; }
          .section { margin-bottom: 32px; }
          .label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 6px; }
          .content { font-size: 16px; white-space: pre-wrap; }
          hr { border: none; border-top: 1px solid #eee; margin: 24px 0; }
          .footer { font-size: 11px; color: #999; margin-top: 40px; }
        </style>
      </head>
      <body>
        <h2>Bhasha Node – Translation Result</h2>
        <hr />
        ${originalText ? `
          <div class="section">
            <div class="label">Original (English)</div>
            <div class="content">${originalText}</div>
          </div>
        ` : ''}
        ${translatedText ? `
          <div class="section">
            <div class="label">Translation</div>
            <div class="content">${translatedText}</div>
          </div>
        ` : ''}
        <div class="footer">Generated by Bhasha Node · ${new Date().toLocaleString('en-IN')}</div>
      </body>
    </html>
  `);
  win.document.close();
  win.focus();
  win.print();
}

// ── Component ──────────────────────────────────────────────────
export default function ResultViewer({ darkMode, result, jobType, onBack }: ResultViewerProps) {
  const border = darkMode ? 'border-white/[0.06]' : 'border-black/[0.06]';
  const bg = darkMode ? 'bg-[#111118]' : 'bg-white';
  const muted = darkMode ? 'text-zinc-500' : 'text-zinc-400';
  const sectionLabel = `text-xs font-semibold uppercase tracking-widest mb-3 flex items-center gap-2 ${muted}`;
  const dlBtn = `flex flex-col items-center justify-center gap-2 px-4 py-4 rounded-xl border text-xs font-semibold transition-all active:scale-95 ${border} ${
    darkMode
      ? 'hover:bg-white/[0.04] hover:border-indigo-500/40 text-zinc-300'
      : 'hover:bg-indigo-50 hover:border-indigo-300 text-zinc-700'
  }`;

  const hasText = !!(result.original_text || result.translated_text);

  return (
    <div className="space-y-4 stagger">

      {/* ── Top bar ── */}
      <div className="flex items-center justify-between animate-fadeUp">
        <button onClick={onBack}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-colors border ${border} ${
            darkMode ? 'text-zinc-300 hover:text-white hover:bg-white/[0.04]' : 'text-zinc-600 hover:text-zinc-900 hover:bg-black/[0.03]'
          }`}>
          <ArrowLeft size={16} /> Translate Again
        </button>
        <span className={`flex items-center gap-2 text-xs font-semibold ${
          darkMode ? 'text-emerald-400' : 'text-emerald-600'
        }`}>
          <CheckCircle size={15} /> Done — 100% Offline
        </span>
      </div>

      {/* ── Video ── */}
      {result.video_url && (
        <div className={`p-5 rounded-2xl border ${border} ${bg} animate-fadeUp`}>
          <div className="flex items-center justify-between mb-3">
            <span className={sectionLabel}><Video size={15} /> Translated Video</span>
          </div>
          <video controls src={result.video_url} className="w-full rounded-xl bg-black" />
        </div>
      )}

      {/* ── Source Text ── */}
      {result.original_text && (
        <div className={`p-5 rounded-2xl border ${border} ${bg} animate-fadeUp`}>
          <span className={sectionLabel}><FileText size={15} /> Original Text</span>
          <p className={`text-sm leading-relaxed ${darkMode ? 'text-zinc-300' : 'text-zinc-700'}`}>
            {result.original_text}
          </p>
        </div>
      )}

      {/* ── Translation ── */}
      {result.translated_text && (
        <div className={`p-5 rounded-2xl border ${border} ${bg} animate-fadeUp`}>
          <span className={sectionLabel}><Languages size={15} /> Your Translation</span>
          <p className={`text-lg font-semibold leading-relaxed ${
            darkMode ? 'text-zinc-100' : 'text-zinc-900'
          }`}>
            {result.translated_text}
          </p>
        </div>
      )}

      {/* ── Audio ── */}
      {result.audio_url && (
        <div className={`p-5 rounded-2xl border ${border} ${bg} animate-fadeUp`}>
          <div className="flex items-center justify-between mb-3">
            <span className={sectionLabel}><Volume2 size={15} /> Voice Output</span>
          </div>
          <audio controls src={result.audio_url} className="w-full h-12" />
        </div>
      )}

      {/* ── Download Panel ── */}
      {(hasText || result.audio_url || result.video_url) && (
        <div className={`p-5 rounded-2xl border ${border} ${bg} animate-fadeUp`}>
          <span className={sectionLabel}><FileDown size={15} /> Save / Download</span>
          <div className={`grid gap-3 ${result.audio_url && result.video_url ? 'grid-cols-4' : result.audio_url || result.video_url ? 'grid-cols-3' : 'grid-cols-2'}`}>

            {/* TXT */}
            {hasText && (
              <button
                onClick={() => downloadTxt(
                  [result.original_text && `Original:\n${result.original_text}`, result.translated_text && `\nTranslation:\n${result.translated_text}`].filter(Boolean).join('\n'),
                  'bhasha-translation.txt'
                )}
                className={dlBtn}
              >
                <FileText size={24} className="text-indigo-400" />
                <span>Text (.txt)</span>
              </button>
            )}

            {/* PDF */}
            {hasText && (
              <button
                onClick={() => printAsPDF(result.original_text, result.translated_text)}
                className={dlBtn}
              >
                <Printer size={24} className="text-rose-400" />
                <span>PDF / Print</span>
              </button>
            )}

            {/* Audio WAV */}
            {result.audio_url && (
              <a href={result.audio_url} download className={dlBtn}>
                <Volume2 size={24} className="text-amber-400" />
                <span>Audio (.wav)</span>
              </a>
            )}

            {/* Video MP4 */}
            {result.video_url && (
              <a href={result.video_url} download className={dlBtn}>
                <Video size={24} className="text-emerald-400" />
                <span>Video (.mp4)</span>
              </a>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
